[package]
name = "m2_sig_tests"
type = "bin"
authors = ["jonybur-oc"]
compiler_version = ">=0.30.0"

[dependencies]
sha256 = { tag = "v0.3.0", git = "https://github.com/noir-lang/sha256" }
keccak256 = { tag = "v0.1.3", git = "https://github.com/noir-lang/keccak256" }
