/**
 * generate-prover-toml.ts
 *
 * Generates a Prover.toml file for the Babylon BABY token eligibility circuit.
 * This lets you run `nargo prove --package private_voting` directly.
 *
 * Usage:
 *   npx ts-node scripts/generate-prover-toml.ts
 *   npx ts-node scripts/generate-prover-toml.ts --voter bbn1abc... --snapshot snapshot/
 *
 * Without --snapshot, uses the synthetic 5-holder demo snapshot.
 * With --snapshot, reads merkle-paths/<address>.json from the snapshot directory.
 *
 * Output: contracts/Prover.toml
 */

import { createHash } from 'crypto';
import * as fs from 'fs';
import * as path from 'path';

const MERKLE_DEPTH = 20;

// ── SHA-256 helpers (must match merkle.nr exactly) ────────────────────────────

function sha256(data: Buffer): Buffer {
  return createHash('sha256').update(data).digest();
}

function hashLeaf(address: string, balance: bigint): Buffer {
  const addrBuf = Buffer.alloc(45, 0); // fixed 45-byte padded address
  Buffer.from(address, 'utf8').copy(addrBuf);
  const balBuf = Buffer.alloc(8);
  balBuf.writeBigUInt64BE(balance);
  return sha256(Buffer.concat([addrBuf, balBuf]));
}

function hashPair(left: Buffer, right: Buffer): Buffer {
  return sha256(Buffer.concat([left, right]));
}

// Build a small power-of-2 tree (not full 2^MERKLE_DEPTH) and pad the remaining
// levels with zero-buffer siblings — matching the approach in babylon-demo.ts.
// This produces the same root that the Noir circuit will compute when verifying.
function buildMerkleTree(holders: { address: string; balance: bigint }[]): {
  tree: Buffer[];
  size: number;
} {
  const leaves = holders.map(h => hashLeaf(h.address, h.balance));

  // Smallest power-of-2 that fits the holders
  let size = 1;
  while (size < leaves.length) size *= 2;

  const tree: Buffer[] = new Array(size * 2 - 1)
    .fill(null)
    .map(() => Buffer.alloc(32));

  for (let i = 0; i < leaves.length; i++) {
    tree[size - 1 + i] = leaves[i];
  }
  // Zero-pad remaining leaves
  for (let i = leaves.length; i < size; i++) {
    tree[size - 1 + i] = Buffer.alloc(32);
  }

  for (let i = size - 2; i >= 0; i--) {
    tree[i] = hashPair(tree[2 * i + 1], tree[2 * i + 2]);
  }

  return { tree, size };
}

function getMerklePath(
  tree: Buffer[],
  size: number,
  leafIndex: number,
): { path: Buffer[]; indices: number[] } {
  const pathBufs: Buffer[] = [];
  const indices: number[] = [];
  let idx = size - 1 + leafIndex;

  while (idx > 0 && pathBufs.length < MERKLE_DEPTH) {
    const isRight = idx % 2 === 0;
    const siblingIdx = isRight ? idx - 1 : idx + 1;
    pathBufs.push(Buffer.from(tree[siblingIdx]));
    indices.push(isRight ? 1 : 0);
    idx = Math.floor((idx - 1) / 2);
  }

  // Pad upper levels with zero buffers — matching babylon-demo.ts behavior
  while (pathBufs.length < MERKLE_DEPTH) {
    pathBufs.push(Buffer.alloc(32));
    indices.push(0);
  }

  return { path: pathBufs, indices };
}

// Compute the root the Noir circuit will arrive at — must match babylon-demo.ts
function computeEffectiveRoot(leaf: Buffer, pathBufs: Buffer[], indices: number[]): Buffer {
  let current = leaf;
  for (let i = 0; i < pathBufs.length; i++) {
    const s = pathBufs[i];
    if (indices[i] === 1) current = hashPair(s, current);
    else current = hashPair(current, s);
  }
  return current;
}

// ── TOML serialization ────────────────────────────────────────────────────────

function bufToTomlArray(buf: Buffer): string {
  return '[' + [...buf].join(', ') + ']';
}

function pathToTomlArray(pathBufs: Buffer[]): string {
  const lines = pathBufs.map(p => '    ' + bufToTomlArray(p));
  return '[\n' + lines.join(',\n') + '\n]';
}

function generateProverToml(
  voter: { address: string; balance: bigint },
  merklePath: Buffer[],
  merkleIndices: number[],
  root: Buffer,
  minBalance: bigint,
): string {
  const addrBuf = Buffer.alloc(45, 0);
  Buffer.from(voter.address, 'utf8').copy(addrBuf);

  return `# Prover.toml — Babylon BABY token Merkle eligibility proof
# Generated by scripts/generate-prover-toml.ts
#
# Voter:       ${voter.address}
# Balance:     ${Number(voter.balance) / 1_000_000} BABY
# Min balance: ${Number(minBalance) / 1_000_000} BABY
# Root:        0x${root.toString('hex')}
#
# Run: nargo prove --package private_voting

address_bytes = ${bufToTomlArray(addrBuf)}
balance = "${voter.balance.toString()}"
min_balance = "${minBalance.toString()}"
path = ${pathToTomlArray(merklePath)}
indices = [${merkleIndices.join(', ')}]
root = ${bufToTomlArray(root)}
`;
}

// ── Demo holders (synthetic snapshot) ────────────────────────────────────────

const DEMO_HOLDERS: { address: string; balance: bigint }[] = [
  { address: 'bbn1demo_voter_alice_000000000000000000xyz', balance: 50_000_000n },
  { address: 'bbn1demo_voter_bob_000000000000000000000ab', balance: 1_000_000n },
  { address: 'bbn1demo_voter_carol_00000000000000000cde', balance: 10_000_000n },
  { address: 'bbn1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq7v3kwf', balance: 2_500_000_000n },
  { address: 'bbn1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqhx5fp4', balance: 5_000_000_000n },
];

const DEFAULT_VOTER = 'bbn1demo_voter_alice_000000000000000000xyz';
const DEFAULT_MIN_BALANCE = 1_000_000n; // 1 BABY in ubbn

// ── CLI ───────────────────────────────────────────────────────────────────────

function main() {
  const args = process.argv.slice(2);
  const voterArg = args[args.indexOf('--voter') + 1] as string | undefined;
  const snapshotDir = args[args.indexOf('--snapshot') + 1] as string | undefined;
  const minBalanceArg = args[args.indexOf('--min-balance') + 1] as string | undefined;

  const minBalance = minBalanceArg ? BigInt(minBalanceArg) : DEFAULT_MIN_BALANCE;

  let voter: { address: string; balance: bigint };
  let merklePath: Buffer[];
  let merkleIndices: number[];
  let root: Buffer;

  if (snapshotDir) {
    // Load from snapshot directory (output of synthetic-snapshot.ts)
    const address = voterArg ?? (() => { throw new Error('--voter required with --snapshot'); })();
    const pathFile = path.join(snapshotDir, 'merkle-paths', `${address}.json`);
    const rootFile = path.join(snapshotDir, 'merkle-root.json');

    if (!fs.existsSync(pathFile)) {
      console.error(`❌ Path file not found: ${pathFile}`);
      process.exit(1);
    }

    const pathData = JSON.parse(fs.readFileSync(pathFile, 'utf8'));
    const rootData = JSON.parse(fs.readFileSync(rootFile, 'utf8'));

    voter = { address, balance: BigInt(pathData.balance) };
    merklePath = pathData.path.map((h: string) => Buffer.from(h, 'hex'));
    merkleIndices = pathData.indices;
    root = Buffer.from(rootData.root, 'hex');

    // Pad to MERKLE_DEPTH if needed
    while (merklePath.length < MERKLE_DEPTH) {
      merklePath.push(Buffer.alloc(32));
      merkleIndices.push(0);
    }
  } else {
    // Synthetic demo snapshot
    const address = voterArg ?? DEFAULT_VOTER;
    const holderIdx = DEMO_HOLDERS.findIndex(h => h.address === address);

    if (holderIdx === -1) {
      console.error(`❌ Voter not in demo snapshot: ${address}`);
      console.error('Available:', DEMO_HOLDERS.map(h => h.address).join('\n  '));
      process.exit(1);
    }

    voter = DEMO_HOLDERS[holderIdx];

    console.log('Building Merkle tree (depth 20)...');
    const { tree, size } = buildMerkleTree(DEMO_HOLDERS);

    const { path, indices } = getMerklePath(tree, size, holderIdx);
    merklePath = path;
    merkleIndices = indices;

    // Effective root = hash after all 20 levels (matching babylon-demo.ts + Noir circuit)
    const leaf = hashLeaf(voter.address, voter.balance);
    root = computeEffectiveRoot(leaf, merklePath, merkleIndices);
  }

  if (voter.balance < minBalance) {
    console.warn(`⚠️  Balance ${voter.balance} < min_balance ${minBalance} — proof will fail eligibility check`);
  }

  const toml = generateProverToml(voter, merklePath, merkleIndices, root, minBalance);

  const outPath = path.resolve(path.join(path.dirname(process.argv[1]), '..', 'contracts', 'Prover.toml'));
  fs.writeFileSync(outPath, toml);

  console.log(`✓ Prover.toml written to ${outPath}`);
  console.log(`  Voter:   ${voter.address}`);
  console.log(`  Balance: ${Number(voter.balance) / 1_000_000} BABY`);
  console.log(`  Root:    0x${root.toString('hex')}`);
  console.log('');
  console.log('Next: nargo prove --package private_voting');
}

main();
